### ISSUE TITLE
User can read a User's Tweets

### ISSUE THREAD

**Issue by mLuby** [ericluby/twitter#2]
API URL:
`GET /users/:userId/tweets`
Success:
[`200 OK`](https://httpstatuses.com/200)`[Tweet {id: Number, username: String, message: String}]`
Error:
[`404 Not Found`](https://httpstatuses.com/404)

- [x] Use [pg](https://node-postgres.com)
- [x] use browser or curl to read JSON

**Comment by ericluby** [comment]
closed by 1ea38f8c2efcbe47bf566f329265969c415338fd
