### ISSUE TITLE
User can create a new Tweet

### ISSUE THREAD

**Issue by mLuby** [ericluby/twitter#3]
API URL:
`POST /users/:userId/tweets`
`{message: String}`
Success:
[`201 Created`](https://httpstatuses.com/201)
Error:
[`400 Bad Request`](https://httpstatuses.com/400)
[`401 Unauthorized`](https://httpstatuses.com/401)
[`404 Not Found`](https://httpstatuses.com/404)

- [ ] use curl to test API

**Comment by ericluby** [comment]
closed by 9779820
