### ISSUE TITLE
User can delete their Tweet

### ISSUE THREAD

**Issue by mLuby** [ericluby/twitter#4]
API URL:
`DELETE /users/:userId/tweets/:tweetId`
Success:
[`204 No Content`](https://httpstatuses.com/204)
Error:
[`401 Unauthorized`](https://httpstatuses.com/401)
[`404 Not Found`](https://httpstatuses.com/404)

- [ ] use `curl -X DELETE  "http://localhost:3000/users/1/tweets/1"` to test API

**Comment by ericluby** [comment]
closed by 8526f63
