### ISSUE TITLE
User can register a new account

### ISSUE THREAD

**Issue by mLuby** [ericluby/twitter#5]
API URL:
`POST /users`
`{un: String, pw: String, email: String}`
Success:
[`201 Created`](https://httpstatuses.com/201)
Error:
[`400 Bad Request`](https://httpstatuses.com/400)
[`409 Conflict`](https://httpstatuses.com/409)
- [ ] collect email, username, password.
- [ ] create new User in DB.
  - [ ] check that email, username are unique.
  - [ ] "salt and hash" password before storing.

**Comment by ericluby** [comment]
closed by 7a66d35
