### ISSUE TITLE
User can login with existing account

### ISSUE THREAD

**Issue by mLuby** [ericluby/twitter#6]
- [x] Collect username (un) and password (pw).
- [x] Use Passport.js with [Local strategy](http://www.passportjs.org/docs/username-password/)
- [x] Store un:pw in browser local storage.
- [x] Attach auth header with un:pw to requests.
- [x] If un:pw match user, allow create/delete.
- [x] If un:pw do not match user, disallow create/delete and return [401 Unauthorized](https://httpstatuses.com/401).

**Comment by ericluby** [comment]
closed by b82dfd9
