### ISSUE TITLE
User can reset password via email

### ISSUE THREAD

**Issue by mLuby** [ericluby/twitter#9]
API URL:
`PUT /users/:userId`
`{pw: String, token: String}`
Success:
[`204 No Content`](https://httpstatuses.com/204)
Error:
[`400 Bad Request`](https://httpstatuses.com/400)
[`401 Unauthorized`](https://httpstatuses.com/401)

1. User clicks "Reset Password" link.
2. User enters account's email.
3. System looks up email. If found, sends email with reset link containing a auth token.
4. User clicks reset link.
5. User enters new password.
6. System changes password for user if auth token is valid.

**Comment by ericluby** [comment]
closed by 9b64e35
